apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-secure-workloads
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-non-root
      match:
        any:
          - resources:
              kinds: ["Pod"]
      validate:
        message: Pods must run as non-root.
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true
    - name: disallow-privilege-escalation
      match:
        any:
          - resources:
              kinds: ["Pod"]
      validate:
        message: Containers must disable privilege escalation.
        pattern:
          spec:
            containers:
              - securityContext:
                  allowPrivilegeEscalation: false
