serviceAccount:
  create: true
cloudWatchLogs:
  enabled: true
  region: us-east-1
  logGroupName: /kubernetes/online-boutique/apps
  autoCreateGroup: true
opensearch:
  enabled: true
  host: replace-with-opensearch-endpoint
  port: 443
  tls: true
resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits: { cpu: 500m, memory: 512Mi }
