replicaCount: 1
image:
  repository: redis
  tag: 7.2-alpine
  pullPolicy: IfNotPresent
service:
  port: 6379
  targetPort: 6379
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
pdb:
  enabled: true
  minAvailable: 1
env: []
