name: build-services
on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - ".github/workflows/build-services.yml"
      - ".github/workflows/reusable-build-service.yml"
  pull_request:
    paths:
      - "src/**"
      - ".github/workflows/build-services.yml"
      - ".github/workflows/reusable-build-service.yml"
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        service:
          - adservice
          - cartservice
          - checkoutservice
          - currencyservice
          - emailservice
          - frontend
          - paymentservice
          - productcatalogservice
          - recommendationservice
          - shippingservice
    uses: ./.github/workflows/reusable-build-service.yml
    with:
      service: ${{ matrix.service }}
      aws-region: us-east-1
    secrets: inherit
